services:
  - type: web
    name: payment-terminal-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://volvo-br-9600-zm5p.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
